### ISSUE TITLE
not working ie11

### ISSUE THREAD

**Issue by mburakerman** [yansern/vue-scrolly#5]
hey! 
thanks for awesome plugin but it's not working on ie11.
would love to see it working on ie11.

do you have any plan to make this work on ie11?

**Comment by bluehaha2** [comment]
I pull request for this bug. You can wait author accept it
Or you can use the fork version

**Comment by mburakerman** [comment]
hi @bluehaha2 
how can i find fork version?

**Comment by bluehaha** [comment]
https://github.com/UniSharp/vue-scrolly
